disabled = false
languageCode = "fr"
languageName = "Français"
weight = 4
title = "ASG LAB"

[params]
  displayName = "Français"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/icon-light.png"
  # secondaryLogo = "img/icon-dark.png"
  # description = "Puissance hydraulique, contrôle absolu."
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "ASG LAB"
   email = "info@asglab.it"
   image = "img/icon-light.png"
   imageQuality = 96
   headline = "Puissance hydraulique, contrôle absolu."
   bio = "Nous sommes spécialisés dans la conception, la construction et la maintenance de systèmes et composants hydrauliques. Nous proposons des solutions sur mesure pour le secteur industriel, alliant expérience, innovation et fiabilité."
   links = [
     { email = "mailto:hello@your_domain.com" },
#     { link = "https://link-to-some-website.com/" },
#     { facebook = "https://facebook.com/username" },
#     { github = "https://github.com/username" },
#     { instagram = "https://instagram.com/username" },
#     { linkedin = "https://linkedin.com/in/username" },
     { telegram = "https://t.me/+393755707492" },
#     { x-twitter = "https://twitter.com/username" },
     { whatsapp = "https://wa.me/+393755707492" },
   ]
