disabled = false
languageCode = "ar"
languageName = "العربية"
weight = 8
title = "ASG LAB"

[params]
  displayName = "العربية"
  isoCode = "ar"
  rtl = true
  dateFormat = "2 January 2006"
  logo = "img/icon-light.png"
  # secondaryLogo = "img/icon-dark.png"
  # description = " القوة الهيدروليكية، التحكم المطلق."
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "ASG LAB"
   email = "info@asglab.it"
   image = "img/icon-light.png"
   imageQuality = 96
   headline = " القوة الهيدروليكية، التحكم المطلق."
   bio = " نحن متخصصون في تصميم وبناء وصيانة أنظمة ومكونات الهيدروليك. نقدم حلولًا مخصصة للقطاع الصناعي، تجمع بين الخبرة والابتكار والموثوقية."
   links = [
     { email = "mailto:hello@your_domain.com" },
#     { link = "https://link-to-some-website.com/" },
#     { facebook = "https://facebook.com/username" },
#     { github = "https://github.com/username" },
#     { instagram = "https://instagram.com/username" },
#     { linkedin = "https://linkedin.com/in/username" },
     { telegram = "https://t.me/+393755707492" },
#     { x-twitter = "https://twitter.com/username" },
     { whatsapp = "https://wa.me/+393755707492" },
   ]
